heat_template_version: 2013-05-23
description: AutoScaling Example
parameters:
  image:
    type: string
    description: Image used for servers
    default: "CentOS 7 Cloud x86_64 (QCOW2)"
  key:
    type: string
    description: SSH key to connect to the servers
    default: gcharot
  flavor:
    type: string
    description: flavor used by the web servers
    default: m1.small

resources:
##### NETWORK #####
  my_network:
    type: OS::Neutron::Net
  my_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: my_network }
      cidr: 10.0.0.0/24
      enable_dhcp: true
      dns_nameservers : [8.8.8.8]

##### LB #####
  my_pool:
    type: OS::Neutron::Pool
    properties:
      description: test_pool
      lb_method: ROUND_ROBIN
      name: my_super_pool
      protocol: HTTP
      subnet_id: { get_resource: my_subnet }
      vip: {"session_persistence" : {type: SOURCE_IP}, "subnet": { get_resource: my_subnet }, "name": my_vip, "address": 10.0.0.42, "protocol_port": 80, "description": my_vip}

##### Computes #####
  web_server_group:
    type: OS::Heat::AutoScalingGroup
    depends_on: my_subnet
    properties:
      min_size: 2
      max_size: 3
      resource:
        type: OS::Nova::Server
        properties:
          flavor:   {get_param: flavor}
          image:    {get_param: image}
          key_name: {get_param: key}
          networks: 
            - network: { get_resource: my_network }
