heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for web servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  net_id:
    type: string
    description: subnet to use
  pool_id:
    type: string
    description: Pool to join
  user_data:
    type: string
    description: Server user_data
  name:
    type: string
    description: Webnode hostname
  metadata:
    type: json


resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      name: {get_param: name}
      networks: 
        - network: { get_param: net_id }
      user_data: {get_param: user_data}
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: 80
